spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/29cm
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /29cm

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 1000

logging:
  level:
    root: WARN
    org:
      hibernate:
        sql: WARN
        type: WARN
---
spring.profiles: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/29cm?serverTimezone=Asia/Seoul&autoReconnect=true&characterEncoding=UTF-8}
    username: root
    password: toor

